default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: wiki_mentat_development
  username: postgres
  password: postgres
  host: 127.0.0.1

test:
  <<: *development
  database: wiki_mentat_test

production:
  primary: &primary_production
    <<: *default
    database: wiki_mentat
    username: wiki_mentat
    password: <%= ENV["WIKI_MENTAT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: wiki_mentat_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: wiki_mentat_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: wiki_mentat_production_cable
    migrations_paths: db/cable_migrate
